bugfix: use ImpredicativeTypes
I get this with GHC 8.0.1:

----------------------------------------
Language/SMTLib2/Pipe.hs:818:24: error:
    • Cannot instantiate unification variable ‘a1’
      with a type involving foralls:
        [Sort]
        -> Sort
        -> (forall arg res.
            (Liftable arg, SMTType res) =>
            SMTFunction arg res -> a)
        -> Maybe a
        GHC doesn't yet support impredicative polymorphism
----------------------------------------

Add ImpredicativeTypes to let this compile; requires a few additional type
annotations to fix resulting over-generalizations.